# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{chkbuild}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{TANAKA, Akira}, %q{Yuki Yugui Sonoda}]
  s.date = %q{2012-01-15}
  s.email = %q{yugui@yugui.jp}
  s.executables = [%q{last-build}, %q{start-build}]
  s.extra_rdoc_files = [
    "README.ja.rd"
  ]
  s.files = [
    "README.ja.rd",
    "Rakefile",
    "VERSION",
    "bin/last-build",
    "bin/start-build",
    "core_ext/io.rb",
    "core_ext/string.rb",
    "erbio.rb",
    "lchg.rb",
    "lib/chkbuild.rb",
    "lib/chkbuild/build.rb",
    "lib/chkbuild/lock.rb",
    "lib/chkbuild/logfile.rb",
    "lib/chkbuild/main.rb",
    "lib/chkbuild/options.rb",
    "lib/chkbuild/scm/cvs.rb",
    "lib/chkbuild/scm/git.rb",
    "lib/chkbuild/scm/svn.rb",
    "lib/chkbuild/scm/xforge.rb",
    "lib/chkbuild/target.rb",
    "lib/chkbuild/targets/gcc.rb",
    "lib/chkbuild/targets/ruby.rb",
    "lib/chkbuild/title.rb",
    "lib/chkbuild/upload.rb",
    "lib/misc/escape.rb",
    "lib/misc/gdb.rb",
    "lib/misc/timeoutcom.rb",
    "lib/misc/udiff.rb",
    "lib/misc/util.rb",
    "sample/build-autoconf-ruby",
    "sample/build-gcc-ruby",
    "sample/build-ruby",
    "sample/build-ruby2",
    "sample/build-ruby3",
    "sample/build-svn",
    "sample/build-yarv",
    "sample/test-apr",
    "sample/test-catcherr",
    "sample/test-co-git",
    "sample/test-co-ruby",
    "sample/test-combfail",
    "sample/test-core",
    "sample/test-core2",
    "sample/test-date",
    "sample/test-dep",
    "sample/test-depver",
    "sample/test-diamond-dep",
    "sample/test-echo",
    "sample/test-env",
    "sample/test-error",
    "sample/test-fail",
    "sample/test-fmesg",
    "sample/test-gcc-v",
    "sample/test-git",
    "sample/test-leave-proc",
    "sample/test-limit",
    "sample/test-make",
    "sample/test-neterr",
    "sample/test-nul",
    "sample/test-opts",
    "sample/test-procmemsize",
    "sample/test-random-neterror",
    "sample/test-savannah",
    "sample/test-sleep",
    "sample/test-stdio",
    "sample/test-timeout",
    "sample/test-timeout2",
    "sample/test-timeout3",
    "sample/test-upload",
    "sample/test-warn",
    "setup/upload-rsync-ssh",
    "test/misc/test-escape.rb",
    "test/misc/test-logfile.rb",
    "test/misc/test-timeoutcom.rb",
    "test/test-util.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/yugui/chkbuild}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6.1}
  s.summary = %q{gemified version of akr's chkbuild - a robust continuous building system}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

